WCASE = 15
HCASE = 10
GCASE = 2
NBRICKSX = 19
NBRICKSY = 14

SCREENSIZE = (int((NBRICKSX*WCASE)+((NBRICKSX+1)*GCASE)),int(((NBRICKSY*HCASE)+((NBRICKSY+1)*GCASE))*3))
effectiveSize = (SCREENSIZE[0],SCREENSIZE[1]+20)
BALLSIZE = 15
TOPWALL = 1
BOTTOMWALL = 0
LEFTWALL = 2
RIGHTWALL = 3
RADIUS = 7

PALETTEHEIGHT = 10 
PALETTEWIDTH = 100000

BRIQUESIZE = (WCASE,HCASE)

l_KEY = 1
r_KEY = 2